baseurl = "https://hackerific.net"
title = "Hackerific"
copyright = "(c) 2015-2019 Matt Foster."
metaDataFormat = "yaml"
theme = "slim"

# Pagination
paginate = 10
paginatePath = "page"

enableEmoji  = true

[permalinks]
    post = "/:year/:month/:day/:title/"

[taxonomies]
    tag = "tags"
    category = "categories"

[author]
    name = "Matt Foster"
    email = "mpf@hackerific.net"

[outputs]
    home = [ "HTML", "JSON", "RSS"]

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    subtitle = "{hacking,music,electronics,radio}"

    # enable commento
    comments = true

    footermsg = 'Powered by <a href="https://gohugo.io">Hugo</a> and <a href="https://github.com/mattfoster/hugo-theme-slim">Slim</a>'

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Google Analytics.
    #googleAnalytics = "UA-7078591-3"
    GoogleSiteVerification = "F0FXChEfil4l5u_1vbWYTwPPjgZ72_OqF4xvoBEnhEs"

    # Sidebar social links.
    githubid = "mattfoster" # Your Github profile ID
    linkedinid = "mattpfoster" # Your LinkedIn profile ID (from public URL)
    twitterid = "mattpfoster" # Your Twitter profile ID
    flickr = "mattfoster"
    # lastfm = "mattfoster"
    callsign = "M0PUH"
    mastodonid = "https://mastodon.radio/@m0puh"
    qrzid = "M0PUJH"

    rss = true

    author = "Matt Foster"


[blackfriday]
    angledQuotes = false
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
