name: mpfblogtest
region: ams
static_sites:
- build_command: rm -r ./public; hugo --destination ./public
  environment_slug: hugo
  github:
    branch: master
    deploy_on_push: true
    repo: mattfoster/hackerific.net
  name: mpfblogtest
