name: Mastodon Archive

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Allows manual triggering

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Mastodon Archive Tool
        run: go install git.garrido.io/gabriel/mastodon-markdown-archive@latest
      
      - name: Run Mastodon Archive Tool
        run: |
          pwd
          ls -al
          mastodon-markdown-archive \
            --user=https://${MASTODON_SERVER}/${MASTODON_USER} \
            --dist=./content/toot/ \
            --threaded=true \
            --exclude-replies=true \
            --exclude-reblogs=true \
            --persist-first=${cursor_file} \
            --since-id=$(test -f $cursor_file && cat $cursor_file || echo "") \
            --limit=40 \
            --download-media=bundle \
            --visibility=public

        env:
          MASTODON_SERVER: "mastodon.radio"
          MASTODON_USER: "m0puh"
          cursor_file: "./data/mastodon-post-cursor"

      - name: Show changes
        run: git status
